Forum/Forum/Controllers/ForumPostController.cs
using Forum.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forum.Controllers
{
    public class ForumPostController : Controller
    {
        //
        // GET: /ForumPost/
        [HttpGet]
        public ActionResult Index(Guid Id)
        {
            ForumThreadModel thread = new ForumThreadModel();
            thread.Id = Id;
            return View("Index", thread.ThreadWithPosts(thread.Id));
        }
        [HttpPost]
       // [ValidateAntiForgeryToken]
        public ActionResult Index(ForumThreadModel thread)
        {
            ForumPostModel newpost = new ForumPostModel();
            newpost.PostText = thread.Comment;
            newpost.Save(thread.Id);
            return View("Index", thread.ThreadWithPosts(thread.Id));
        }           
    }
}

Forum/Forum/Views/ForumPost/Index.cshtml
@model Forum.Models.ForumThreadModel
@{         
    ViewBag.Title = "Threads with posts";
}
<html>
     <head>
    <title>Threads with posts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="/Content/strap/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<link href="/Content/strap/css/bootstrap-responsive.min.css" rel="stylesheet">
  </head>
<body>
  //  @Html.AntiForgeryToken()
    @using( Html.BeginForm("Index","ForumPost",FormMethod.Post))
       {
       @Html.Label("Thread Title: ") @Model.Title.ToString()
        @Html.Label("Description: ")@Html.Label(Model.Description.ToString())
           if (Model.Posts!=null)
            { 
        <table border="1" style="font-size: medium;">
            <tr>
                <td>PostId</td>
                <td>PostText</td>
                <td>CreationDate</td>
            </tr>
            @foreach (Forum.Models.ForumPostModel item in Model.Posts)
                 {
                <tr>
                    <td>@Html.Label(item.Id.ToString())</td>
                    <td style="font-size: large">          
                     @Html.ActionLink((item.PostText.ToString()!=string.Empty)?item.PostText:"NO Text","#", new {id=item.Id.ToString()})</td>
                     @*@Html.Label((item.PostText.ToString()!=string.Empty)?item.PostText:"NO Text")</td>*@
                    <td>@Html.Label(item.CreationDate.ToString())</td>
                </tr>
                }
            </table>
    //    Forum.Models.ForumPostModel newpost =new Forum.Models.ForumPostModel();        
     <label style="font-weight:bold">Add Your Comment Here: </label> @Html.TextBox("Comment")                 
       //         Model.Posts.Add(newpost);
        @Html.HiddenFor(x=>x.Posts)
          <button class="btn-info" style="border-color:black">Add Your Comment</button>
            }
      }
</body>    
</html>