Forum/Forum/Controllers/ForumSectionController.cs
using Forum.ClassLibrary;
using Forum.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forum.Controllers
{
    public class ForumSectionController : Controller
    {
        //
        // GET: /ForumSection/
        [HttpGet]
        public ActionResult Index()
        {
            ForumSectionModel model = new ForumSectionModel();
            return View(model.Show());
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(List<ForumSectionModel> model)
        {
            model[0].Save();
            return View(model[0].Show());
        }
        [HttpGet]
        public ActionResult ViewSections()
        {
            ForumSectionModel model = new ForumSectionModel();
            return View(model.Show());
        }
        [HttpPost]
        public ActionResult ViewSections(ForumSectionModel model)
        {
            ForumSection section = new ForumSection();
            section.Name=model.Name;
            return View(model.Show());
        }
    }
}

Forum/Forum/Views/ForumSection/Index.cshtml
@model List<Forum.Models.ForumSectionModel>
@{
    ViewBag.Title = "Sections";
}
<html>
    <body>
    @Html.AntiForgeryToken()  
        @using( Html.BeginForm("Index","ForumSection",FormMethod.Get))
        {<fieldset style="width:300px;grid-row-sizing:auto">
                        <legend style="border :initial; color:darkolivegreen;text-align:left"> All Sections</legend>                        
            <table border="1" style="font-size:medium;">
            <tr>
             <td>SecionId</td>
            <td>Name</td>
            <td>DisplayOrder</td>
            </tr>
        @foreach (Forum.Models.ForumSectionModel item in Model)
        {<tr>
             <td>@Html.Label(item.Id.ToString())</td>
            <td style="font-size:large">@Html.ActionLink(item.Name,"../ForumThread/Index", new {id=item.Id.ToString()})</td>
           @* @Html.ActionLink("linktext","actionname","routevalue object",
            *@<td>@Html.Label(item.DisplayOrder.ToString())</td>
            </tr>
        }
            </table>
            </fieldset>
        }
        @using (Html.BeginForm("Index","ForumSection",FormMethod.Post))
        {
    @Html.AntiForgeryToken() 
            Model.RemoveRange(0, Model.Count);
            Model.Add(new Forum.Models.ForumSectionModel());
            //int i = Model.Count - 1;
            <fieldset style="width: 300px;">
                <legend style="border: initial; color: darkolivegreen; text-align: left;">Add New Section: Admin Panel</legend>
                <table style="border:thin"><tr><td>
                @Html.Label("Section Name:") @Html.TextBoxFor(x => x[(0)].Name, new { style = "width:180px;" })
                </td><td>
                @Html.Label("DisplayOrder:") @Html.TextBoxFor(x => x[(0)].DisplayOrder, new { style = "width:110px;" })
                </td></tr></table>
                <input type="submit" value="Save" />
            </fieldset>
        }
        </body>
    </html>

Forum/Forum/Views/ForumSection/ViewSections.cshtml
@model List<Forum.Models.ForumSectionModel>
@{
    ViewBag.Title = "ViewSections";
}

<h2>ViewSections</h2>
<html>
    <body style="font:500">
        <table>
        @foreach (Forum.Models.ForumSectionModel item in Model)
        {<tr>
            <td>@Html.ActionLink(item.Name,"ViewSections")</td>
            <td>@Html.Label(item.DisplayOrder.ToString())</td>
            </tr>
        }</table>
    </body>
</html>