Forum/Forum/Controllers/ForumUserController.cs
using Forum.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forum.Controllers
{
    public class ForumUserController : Controller
    {
        //
        // GET: /ForumUser/

        public ActionResult Index()
        {
           // ForumUserModel model = new ForumUserModel();           
            return View(ForumUserModel.ShowAllUser());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(List<ForumUserModel> model)
        {
            //Validator.ValidateValue(model.Name,
            //Validator.TryValidateValue(model,.Required();
            ForumUserModel.Save(model[0]);
            return View(ForumUserModel.ShowAllUser());
        }
    }
}

Forum/Forum/Views/ForumUser/Index.cshtml
@model List<Forum.Models.ForumUserModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    <title>User Creation with validation</title>
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.6.2.js">
    </script>
    <script
        src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.8.1/jquery.validate.js">
    </script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js">
    </script>
    <script>
        function IsCellNo() {
            var val = document.getElementById('itemcellno').value
            //var exp = /^[0][1][0 - 9]{11}/;
            if (val == "" || isNaN(val) || exp.test(val)) { lblCellNo.innerText = "Plz enter valid cell number"; return false; }
            else { lblCellNo.innerText = " "; return true; }
        }
        function check() {
            var nvalue = document.getElementById('itemname').value
            if (nvalue == "") { lblName.innerText = "User Name is Required"; return false; }
            else { lblName.innerText = ""; }

            var cellno = document.getElementById('itemcellno').value
            if (cellno == "") { lblCellNo.innerText = "Cell No is Required"; return false; }
            else { lblCellNo.innerText = ""; }

            var nid = document.getElementById('itemnid').value
            if (nid == "") { lblNid.innerText = "Nid is Required"; return false; }
            else { lblNid.innerText = ""; }

            return true;
        }
    </script>
</head>
  <body>
    @Html.AntiForgeryToken()  
        @using( Html.BeginForm("Index","ForumUser",FormMethod.Get))
        {<fieldset style="width:300px;grid-row-sizing:auto">
                        <legend style="border :initial; color:darkolivegreen;text-align:left"> All Users</legend>                        
            <table border="1" style="font-size:medium;">
            <tr>
             <td>Name</td>
            <td>Nid</td>
            <td>Cellno</td>
            </tr>
        @foreach (Forum.Models.ForumUserModel item in Model)
        {<tr>
             <td>@Html.Label(item.Name.ToString())</td>
            @*<td style="font-size:large">@Html.ActionLink(item.Name,"../ForumThread/Index", new {id=item.Id.ToString()})</td>*@
             <td>@Html.Label(item.Nid.ToString())</td>
            <td>@Html.Label(item.Cellno.ToString())</td>
            </tr>
        }
            </table>
            </fieldset>
        }
        @using (Html.BeginForm("Index", "ForumUser", FormMethod.Post, new { onsubmit = "return check()" }))
        {
    @Html.AntiForgeryToken() 
            Model.RemoveRange(0, Model.Count);
           Model.Add(new Forum.Models.ForumUserModel());
            //int i = Model.Count - 1;
            <fieldset style="width: 300px;">
                <legend style="border: initial; color: darkolivegreen; text-align: left;">Add New User: Admin Panel</legend>
                <table style="border: thin">
                    <tr>
                        <td>
                            @Html.Label("User Name:") @Html.TextBoxFor(x => x[(0)].Name, new { id = "itemname" })
                            <label id="lblName" style="color: red"></label>
                        </td>
                        <td>
                           @* <input type="text" name="x => x[(0)].CellNo" id="nameid" value="" onblur="return fuckyou()" />*@
                              @Html.Label("Cell No:") @Html.TextBoxFor(x => x[(0)].Cellno, new { id = "itemcellno",@onblur=" return IsCellNo()" })
                            <label id="lblCellNo" style="color: red"></label>
                        </td>
                        <td>
                            @Html.Label("Nid:") @Html.TextBoxFor(x => x[(0)].Nid, new { id="itemnid" })
                            <label id="lblNid" style ="color:red"></label>
                        </td>
                    </tr>
                </table>
              
                <input type="submit" value="Save" />
            </fieldset>
        }
        </body>
</html>