Forum/Forum/Controllers/ForumThreadController.cs
using Forum.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forum.Controllers
{
    public class ForumThreadController : Controller
    {
        //
        // GET: /ForumThread/
        [HttpGet]
        public ActionResult Index(Guid id)
        {
            ForumThreadModel Thread = new ForumThreadModel();
            Thread.ParentId = id;
            return View("Index",Thread.ShowByParentId(Thread.ParentId).ToList());
          //  return View("ThreadsBySection", Thread.ShowByParentId(Thread.Id));
        }
        public ActionResult AddThread(string ThreadId)
        {
            return View(new ForumThreadModel());
        }
         [HttpPost]
        public ActionResult AddThread(ForumThreadModel model)
        {
            return View(new ForumThreadModel());
        }
         [HttpPost]
         [ValidateAntiForgeryToken]
         public ActionResult Index(List<ForumThreadModel> model)
         {
             model[0].Save(model[0].ParentId);
             return View("Index", new ForumThreadModel().ShowByParentId(model[0].ParentId).ToList());
         }

    }
}

Forum/Forum/Views/ForumThread/Index.cshtml
@model List<Forum.Models.ForumThreadModel>
@{
    ViewBag.Title = "Threads of Section";
}
<html>
     <head>
    <title>Bootstrap 101 Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="/Content/strap/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<link href="/Content/strap/css/bootstrap-responsive.min.css" rel="stylesheet">
  </head>
    <body>
    @Html.AntiForgeryToken()  
        @using( Html.BeginForm("Index","ForumThread",FormMethod.Get))
        {
            <fieldset style="width:300px;grid-row-sizing:auto">
                        <legend style="border :initial; color:darkolivegreen;text-align:left"> All Threads of Section:@Model[0].ParentId</legend>                                      
            @if (Model[0].Id != Guid.Empty)
            { 
                <table border="1" style="font-size:medium;">
            <tr>
             <td>ThreadId</td>
            <td>Name</td>
            <td>Description</td>
            </tr>
        @foreach (Forum.Models.ForumThreadModel item in Model)
        {
            <tr>
             <td>@Html.Label(item.Id.ToString())</td>
            <td style="font-size:large">
                @Html.ActionLink((item.Title.ToString()!=string.Empty)?item.Title:"NO Title","../ForumPost/Index", new {id=item.Id.ToString()})</td>
           @* @Html.ActionLink("linktext","actionname","routevalue object",
            *@<td>@Html.Label((item.Description!=string.Empty)?item.Description:"No Description")</td>
            </tr>
        }
            </table>
            }
            else { <label style="font-size:x-large">No Threads..</label>}
            </fieldset>
        }
       @* @if(Model.Count!=0)
        {*@
            @using (Html.BeginForm("Index","ForumThread",FormMethod.Post))
        {
    @Html.AntiForgeryToken() 
            @Html.HiddenFor(x=>x[0].Id)
            @Html.HiddenFor(x=>x[0].ParentId)
        Guid threadid = Model[0].Id;
        Guid ParentId = Model[0].ParentId;
        Model.RemoveRange(0, Model.Count);
        Model.Add(new Forum.Models.ForumThreadModel());
        foreach (Forum.Models.ForumThreadModel item in Model)
        {
           // Forum.Models.ForumThreadModel item = new Forum.Models.ForumThreadModel();
            item.ParentId = ParentId;
            //item.Id = threadid;
            item.Description = string.Empty;
            item.Title = string.Empty;
        } @Html.HiddenFor(x=>x[0].ParentId)
            //int i = Model.Count - 1;
            <fieldset style="width: 300px;">
                <legend style="border: initial; color: darkolivegreen; text-align: left;">Add New Thread: Section-@Model[0].ParentId</legend>
               
                <table style="border:thin"><tr><td>
                @Html.Label("Title:") @Html.TextBoxFor(x => x[(0)].Title, new {placeholder="Give Title", style = "width:180px;",@class="form-control"})
                     
                </td><td>
                @Html.Label("Description:")  @Html.TextBoxFor(x => x[(0)].Description, new { placeholder="Write a Description",style = "width:110px;",@class="form-control" })
                </td></tr></table>   
              <button class="btn-info" style="border-color:black">Add a Thread</button>
            </fieldset>
                @*Model[0].Posts.Add(new Forum.Models.ForumPostModel());
                @Html.TextBoxFor(z=>z[0].Posts[0].PostText,new {@class="form-control"})*@
        }
        </body>    
    <script src="/Content/strap/js/jquery.js"></script>
    <script src="/Content/strap/js/bootstrap.min.js"></script>
    </html>

Forum/Forum/Views/ForumThread/ThreadsBySection.cshtml
@model List<Forum.Models.ForumThreadModel>
@{
    ViewBag.Title = "ThreadsBySection";
}

<h2>ThreadsBySection</h2>
<body>
   @* @Html.LabelFor(x=>x.Title):@Html.TextBoxFor(x=>x.Title)*@
    @if (Model != null)
             {
                 int i = 0;
                 var gd = new WebGrid(Model, canPage: true); 
        @gd.GetHtml(tableStyle: "webGrid table-hover table-bordered",
        headerStyle: "header", caption: "Threads..",
        alternatingRowStyle: "alt", rowStyle: "rowStyle",
                                                htmlAttributes: new { id = "Datatable"},

                columns: gd.Columns(
                gd.Column("Title", format: (item) => Html.ActionLink(Model[i++].Title, "AddThread", new { id = item.ThreadId.ToString() })),
            //gd.Column("Card", format: (item) => item.GetSelectLink(item.Card)),
             //   gd.Column("Card_Name", "Card Name", canSort: false, style: "width:200px;font-weight:bold;"),
                gd.Column("Id", "Section", canSort: false),
                gd.Column("ThreadId", "Thread", canSort: false)
         ))
             }
</body>